### ISSUE TITLE
Use a private docker registery

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#1]
The agent can be built ahead of time using a specific buildpack. We could then use the image to launch the agent from the master server.

**Comment by netgusto** [comment]
Yes. We would need one BP per technology supported, right ?

OTOMH :
* nodejs, python, ruby, lua for interpreted langages
* c, c++14, golang, rust, swift for compiled languages
* maybe also plain image for binary blobs (not compiled on site) ? Do we even support those ?

**Comment by netgusto** [comment]
No buildpack; all we expect is a Dockerfile.
The private repo is up. It's security is still a concern though (tracked in #65)
