### ISSUE TITLE
Enable https:// and wss:// on all frontend facing services

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#101]
And https:// and wss://

HAProxy to the rescue ?
Using letsencrypt.org certbot

**Comment by xtuc** [comment]
Enabled TLS on the following domains:
- bytearena.com
- docker-agentbuilder-socket-proxy.net.bytearena.com
- graphql.net.bytearena.com
- live.bytearena.com
- mq.net.bytearena.com
- registry.net.bytearena.com
- replay.bytearena.com
- static.bytearena.com

**Comment by xtuc** [comment]
docker-agentbuilder-socket-proxy.net.bytearena.com is now HTTP because of the Docker client. It's only used internally.
