### ISSUE TITLE
Security: Harden docker network isolation

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#102]
To avoid docker containers changing their NICs configuration to switch their subnet (agents) and access unauthorized services in the backend subnet, we should drop all capabilities allowing them to reconfigure their NICs.

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

```
--drop-cap=ALL --add-cap=...(only those we need)
```

**Comment by xtuc** [comment]
- disable icc in the docker deamon
- use net.bytearena.com domains

**Comment by netgusto** [comment]
ALL caps are already dropped; see https://github.com/ByteArena/bytearena/blob/4679bdcff36e7e2d814af399ed4930d6f04187f2/arenaserver/container/orchestrator.go#L170

**Comment by xtuc** [comment]
Agents are now separate in a different Docker daemon and subnet.
