### ISSUE TITLE
Run agent containers without root

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#110]
Actuellement on attribue le running process à root dans les containers agent

https://github.com/ByteArena/bytearena/blob/aa4d990d1550c3c1ab6454a7008ed6f614ee7fae/arenaserver/container/orchestrator.go#L157

Il est préférable que ce ne soit pas le cas.
Sur quel user binder, sachant qu'on ne maitrise pas la distro ?

**Comment by netgusto** [comment]
Une piste : le compte `nobody`

https://askubuntu.com/questions/329714/what-is-the-purpose-of-the-nobody-user

Et surtout : https://askubuntu.com/a/329717

**Comment by xtuc** [comment]
Related commit 0ad2a6da8c4e9000569fba2e1e6efd049e73136e
