### ISSUE TITLE
Security: Hardened docker and containers

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#122]
* Disable SUIDs on executables : https://blog.tutum.co/2015/02/03/hardening-containers-disable-suid-programs/

* Find a way to prevent the reusing of local base images (`FROM someoneelse/super-agent`)

**Comment by xtuc** [comment]
Interdire namespaces (analyse statique du Dockerfile et HAProxy) :
- bytearena/*
- registry.net.bytearena.com*

**Comment by netgusto** [comment]
PR en cours: #127.

**Comment by netgusto** [comment]
* [x] Les images privées BA doivent être dans le NS bytearena/
* [x] Les images des agents doivent être dans le NS bytearena/agent/
* [x] l'analyse statique doit interdire ces NS.
