### ISSUE TITLE
MVP - Request for comments

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#13]
What would the MVP be like ?
I think we should settle on a feature list, then derive a task list, affectable to contributors depending on motivation / resources.

First step : add to this issue everything you think required for a closed beta access MVP.

**Comment by xtuc** [comment]
- [x] Agents
  - [x] Support for JavaScript
  - [x] Built using a builtpack
  - [x] [Null route](https://en.wikipedia.org/wiki/Null_route) internet (#7)

- [x] Game engine
  - [x] Agents have a world perception (other agents)
  - [x] Agents are constrained to physics
  - [x] Error handling (agents crash, tick timeout, ...)

- [x] Web interface
    - [x] Realtime visualization

**Comment by netgusto** [comment]
* Deathmatch arena (n agents, 2 < n < 8)
* agent : ability to shoot
* agent : level of energy (resource scarcity forces to implement a finer management than just "run" and "shoot")
* backend web interface : launch and monitor arenas **=> NOT MVP**
* frontend web interface : push agent code, register for tournament

**Comment by edi9999** [comment]
I agree with all of the above. 

I would add : 

- [x] For the deathmatch arena : some basical agents of level (easy, medium, hard) written by us.
- [x] For now, only competition, no collaboration
- [x] Be able to collect logs of your agents : https://github.com/netgusto/bytearena/issues/7#issuecomment-290676924

**Comment by netgusto** [comment]
* [x] Obstacles
* [x] Perception : Vision (including vision occlusion by obstacles)

**Comment by netgusto** [comment]
Closing, as it seems we checked all the boxes ! yay !
