### ISSUE TITLE
Working session > Sat 19/8

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#135]
### Game scheduling strategy?
- What about an endless game for the demo?
- How could we give the user the impression that many games are being played at that time?

### Resilience/correctness issues on arena-master
- Since it's asynchronous we need to make sure that the game requested by the user is available/launched. The state of Arena-master isn't always correct in that sense. See  
https://github.com/ByteArena/bytearena/issues/90 https://github.com/ByteArena/bytearena/issues/89

### Landing page

At least publish the current pr : https://github.com/ByteArena/bytearena.com/pull/15

**Comment by netgusto** [comment]
lol :)
