### ISSUE TITLE
Handle better handshake timeouts with go

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#143]
https://github.com/ByteArena/bytearena/blob/cd95b321b8686dcd33aa7e3cdb7519306941f5c9/arenaserver/comm/server.go

**Comment by xtuc** [comment]
Related to #94

**Comment by xtuc** [comment]
Mark the agent died and launch the arena

**Comment by xtuc** [comment]
Fixed in https://github.com/ByteArena/bytearena/commit/f65d83b29bf0afc8a539316b9e55d88f6f29500e
