### ISSUE TITLE
Limiting the acceleration and angular acceleration

### ISSUE THREAD

**Issue by edi9999** [ByteArena/backends#15]
In the real world, it is not possible to have an acceleration that goes in 1ms from (1,0) to (-1,0) (eg have a discontinuity in the acceleration).

One way to do this would be to use the `jerk` (https://en.wikipedia.org/wiki/Jerk_(physics)) , which is the rate of change of acceleration. Jerk is to acceleration what acceleration is to speed.

We can also limit the angular acceleration with angular jerk : https://en.wikipedia.org/wiki/Angular_acceleration#References

To make this work, the intents of agents need to be expressed in `jerk` instead of `acceleration`. We would still need to have an upper limit for `acceleration` and for `angular acceleration` (and also for velocity and angular velocity)

**Comment by netgusto** [comment]
@edi9999 Would you prototype the jerk ?

**Comment by netgusto** [comment]
I'll prototype the angular acceleration management.

**Comment by netgusto** [comment]
* Angular displacement: angle of rotation around an axis; static property of an object
    * corresponds to the rotation of an object (not it's change over time, just the rotation state of the object, as measured perhaps in radians or degrees)
* Angular velocity: rate of change of angular displacement; vector of angular speed of an object, and axis of rotation
    * vitesse de rotation en radians/s
* Angular acceleration is the rate of change of angular Velocity
    * radians/(s*s)
* Torque: torsion force; rate of change of angular momentum
* Moment of inertia: torque needed to obtain a desired angular acceleration around an axis

==============
Tableau "Classical mechanics SI units" détaillant le rapport entre chaque dimensions temps, masse, et moment d'inertie, et les unitées utilisées en dimension^1, dimension^2 et dimension^3
https://en.wikipedia.org/wiki/Angular_acceleration

**Comment by netgusto** [comment]
http://www.red3d.com/cwr/steer/gdc99/

> Because of its assumption of velocity alignment, this simple vehicle model cannot simulate
> effects such as skids, spins or slides. **Furthermore this model allows the vehicle to turn
> when its speed is zero**. Most real vehicles cannot do this (they are “non-holonomic”)
> and in any case it allows undesirably large changes in orientation during a single time step.
>
> This problem **can be solved by placing an additional constraint on change of orientation**,
> **or by limiting the lateral steering** component at low speeds,
> **or by simulating moment of inertia**.

**Comment by netgusto** [comment]
> This model allows the vehicle to turn when its speed is zero.  Most real vehicles cannot do this (they are “non-holonomic”)

Will try this to solve this problem like this :

> placing an additional constraint on change of orientation,

**Comment by netgusto** [comment]
* [x] prototype the angular velocity constraint
* [x] prototype the acceleration constraint
* [ ] prototype the jerk management

**Comment by netgusto** [comment]
angular velocity management done in https://github.com/netgusto/bytearena/pull/38

**Comment by netgusto** [comment]
Acceleration contraint is handled in #42.
Also, angular velocity is now function of speed (also #42).

Jerk (speed/second cube = rate of change of acceleration) will not be implemented for now.

Will close when #42 is merged.
