### ISSUE TITLE
Gameplay: Death & respawn when fragged

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#155]
Like in other FPS games, respawn when dead; agent with most kills win the game.

**Comment by netgusto** [comment]
Frag and respawn implemented. Still need to implement scoring (backend + viz + perception)

**Comment by xtuc** [comment]
I can implement a ScoreSystem + emit events to update the viz accordingly. 

Note that the PR for events is not the priority for now.

**Comment by netgusto** [comment]
Done, and scoring also.
