### ISSUE TITLE
[MQ] Redis retry mechanism?

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#173]
Following https://github.com/ByteArena/bytearena/pull/169

**Comment by netgusto** [comment]
Milestone ?

**Comment by xtuc** [comment]
Works great without it. I need to think a bit more about it. We can add this to the alpha prior 1 milestone.

**Comment by xtuc** [comment]
No needed now. This was useful with the old mq implementation since it had to reconnect every once in a while and message could get lost during the process.
Redis subscriptions are stable enough.
