### ISSUE TITLE
Prototype the usage of a message broker

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#2]
A message broker like Kafka would enable:
- Agent (consumer) lag detection
- Message history
- Message replay
- At-least-one delivery
- Distributing across nodes

**Comment by netgusto** [comment]
Do you think you could spin up a prototype implementation for this particular setup ?

**Comment by xtuc** [comment]
Sure thing! https://kafka.apache.org/quickstart

**Comment by xtuc** [comment]
Closing since we are using mq
