### ISSUE TITLE
Package agent SDK (javascript only)

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#23]
We should package a client SDK to be used by all our agent implementations (js only for now).

See https://github.com/netgusto/bytearena/pull/20/files/9fdf18b740bacff406f1b74d3692df0ea4f06df7#r109691370

What the SDK will be is TBD (npm module ? single file to dl ? something else ?)

**Comment by netgusto** [comment]
Also, the refactoring of agents is necessary once SDK is complete.

**Comment by xtuc** [comment]
An open-source SDK is OK, publish it on npm, tell the users how to use it in a documentation.

**Comment by netgusto** [comment]
You removed the up-for-grabs but assigned no one ?

**Comment by netgusto** [comment]
SDK and refactoring done.

See :
* Visualization : Commit https://github.com/netgusto/bytearena/pull/52/commits/bf40b6dc036ae24eb0b8a9f55c094a399d754af7
* Agent refactoring : https://github.com/netgusto/bytearena-agent-seeker
* SDK repo : https://github.com/netgusto/bytearena-sdk-javascript and https://www.npmjs.com/package/bytearena-sdk on npm
