### ISSUE TITLE
Hardened containers

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#3]
Right now, containers are secured like so:

* they do not run their process with root
* all their linux capacities are dropped (`--cap-drop ALL`)
* they have no access to the docker socket `/var/run/docker.sock`
* they are constrained in memory (32M) and CPU share (5%) per container

They use these resources though :
* networking
* their source code mountpoint (access to host FS on a specific folder)

How to improve this ?

Further hardening : https://blog.jessfraz.com/post/getting-towards-real-sandbox-containers/

Also : use rkt instead of docker ?

Objective : reach sandbox grade containment.

**Comment by xtuc** [comment]
Related to #1

**Comment by xtuc** [comment]
Ok via https://github.com/ByteArena/bytearena/issues/102
