### ISSUE TITLE
Paradigm shift: Pivot from TickLoop to RefreshLoop

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#35]
* **A/** Actuellement: tickloop gérée côté serveur
    * Avantages:
        * modèle turn based => ticks de même durée
        * updates batchables
        * mutations batchables
        * getperception alignés avec les mutations
    * Inconvénients:
        * bursts de tick => congestion réseau
        * obligation de gérer un timeout par tour
        * clients forcés de mettre à jour dans un temps contraint et invariable, sous peine de timeout

* **B/** Possibilité évoquée: tickloop gérée par les clients
    * Avantages:
        * permet de gérer chaque client à son rythme
        * plus de timeout à gérer
    * Inconvénients:
        * Les updates du state du monde ne peuvent plus être batchés; il faut traiter les updates après chaque pushmutation

* **C/** Possibilité évoquée: plus de tickloop, mais une refreshloop
    * Similaire à A
    * Le serveur gère une loop, et pousse les perceptions à intervales réguliers à tous les agents (refresh loop); contrairement à **A/**, les 
    * Les agents peuvent soumettre des mutations à tout moment, sans problème de timeout, et en utilisant le temps qui leur est nécessaire pour le faire
    * Avantages:
        * Pas de timeout
        * Pas de bursts de communications en un seul instant (au début de chaque tick en **A/**) => lissage des communications dans le temps, et donc meilleure utilisation des ressources système
        * Chaque client peut traiter les données et calculer ses mutations à son rythme
    * Inconvénients
        * Nécessité de mettre en place une gestion adaptée des queues de traitement des mutations pour garantir une prise en compte des mutations en moins de 2 frames maximum (c'est à dire si poussé en frame f, pour la frame f+1 ou f+2 au plus tard)

**Comment by netgusto** [comment]
Autres délibérations :

* nécessité d'un canal d'évènements parallèles aux perceptions ? => oui si **B/**, non dans les autres cas, car perception toujours à jour au niveau de l'agent

* Si **B/** ou **C/** => imposer une limite de mutations par seconde (par tour ? comment faire ?)
    * bloquer si limite dépassée

* Si **B/** ou **C/** => la physique devient fonction du temps mur (et plus du tick)

**Comment by xtuc** [comment]
![image](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQnl0ZUFyZW5hCgpTZXJ2ZXIgYmFja2VuZC0-AAoGOiBpbml0ABYHLT5TREsgQWdlbnQ6IHNwYXduCgAICS0-ABMFIEEABxMAQwhSZXF1ZXN0IHBlcmNlcHRpb24ARBVlbmQAFwwAUQcAcA1nZQA4DgByFAA4D25vdGUgcmlnaHQgb2YAgT8GIEE6IHRoaW5rAFkLAIFvBwCBAAVtdXRhAIEYDgCCFw06IGVucXVldWUAByJwcm9jZXNzAEkJIAAzBQCCWxluZXcgc3RhdGUAgX1J&s=default)

**Comment by netgusto** [comment]
Done; implemented **C/**
