### ISSUE TITLE
Use helper for the panic

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#39]
I found this in Golang's documentation.

![screenshot from 2017-04-15 15-47-23](https://cloud.githubusercontent.com/assets/1493671/25064069/e9342056-21f2-11e7-8c2a-7328208def09.png)

I like the `check` function, should we use it across the codebase?

**Comment by netgusto** [comment]
Only problem I see is that the stack trace would be raised from a different place than the incriminated code; problem ?

Apart for that, LGTM; when we'll have defined a real strategy for error handling, this will be easily refactorable.

**Comment by xtuc** [comment]
It won't break the stack trace. This will add a function call on top of the stack (the error handler)

**Comment by netgusto** [comment]
Done in #52.
