### ISSUE TITLE
TCP or UDP between agents and server ?

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#5]
Right now, the streams between the server and agents of an arena is implemented with TCP.

* Would using UDP yield better performance ?
* At what cost ? Reliability ? Would this cost be acceptable / this risk be negligable ?

Also, cross check with #2

**Comment by edi9999** [comment]
If I understand correctly, we could use any of these for communication between agents and server : 

* UDP
* TCP 
* HTTP2
* Kafka (maybe only for server to agent, but not from agent to server)
* Websocket

The underlying question behind this is also : do all agents reside on the same host as the agent or not ? 

If they reside on the same host (for example with 20 agents max for one game), then the connection is very reliable, so using a high-level communication method will not harm the latency. However, the less reliable the connection is, the higher the latency, in particular for high-level protocols.

In my opinion, a game is played with a max of 20 agents, so I would prefer to use the higher level methods (eg Websocket or even HTTP2).

If we have 20 agents with 10 Moves Per Second, we have **only** 200 requests to make per second, which is not a lot at all for HTTP.

The fear that I have with UDP is that the code that we write will be handling a lot of things that TCP (for reliability) or HTTP (structure) already handle very well for us.

For example slither.io handles 500 users in parallel with a **websocket** connection with 50FPS, so it is about 25000 communications per second.

**Comment by netgusto** [comment]
> The fear that I have with UDP is that the code that we write will be handling a lot of things that TCP (for reliability) or HTTP (structure) already handle very well for us.

Yes, I share this opinion *a priori*. If TCP becomes a problem (latency, or lack of structure) we'll pivot and explore alternative solutions. For now, TCP does the job reasonably well.

> The underlying question behind this is also : do all agents reside on the same host as the agent or not ?

I'd say yes, because I don't see what could be gained by splitting a single arena instances across multiple machines.

**Comment by netgusto** [comment]
Can be closed for me.

**Comment by xtuc** [comment]
LGTM :+1: 

> Kafka (maybe only for server to agent, but not from agent to server)

We can use it for both directions, using two topics.

**Comment by netgusto** [comment]
> Yes, I share this opinion a priori. If TCP becomes a problem (latency, or lack of structure) we'll pivot and explore alternative solutions. For now, TCP does the job reasonably well.

See #19 for problems discovered; see #32 for possible resolution.
