### ISSUE TITLE
Dotgit port 9418 : Bypass SSH logic (key, auth, perms, etc) ?

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#58]
The files docker-compose.*.yml reference port 9418 for dotgit. Is that cool ?

**Comment by xtuc** [comment]
Je n'utilise plus docker-compose en prod

**Comment by xtuc** [comment]
Removed port in https://github.com/ByteArena/ansible-deploy/commit/f8f02cc57854c52a8f9468b7de34d4b29eeb423a
