### ISSUE TITLE
Dotgit > incorrect repoName in post-receive hooks

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#66]
Given

```
remote: GIT_REPO_NAME=xtuc/stalall:latest
remote: GIT_REPO_PATH=/home/git/repositories/1/22.git
```

Agentbuilder will try to clone ` git@dotgit:xtuc/xtuc/stalall:latest.git into /tmp/xtuc/xtuc/stalall:latest`.

### TODO

- Remove duplicated username
- Remove latest tag

**Comment by netgusto** [comment]
Solved.
