### ISSUE TITLE
No internet access for agents

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#7]
Agents should have no internet access.

If they did :
* they could be remote controlled by a human operator, and we do not want that;
* they could access the arena live stream, which would give them a vantage point, and we do not want that.

**Comment by xtuc** [comment]
Thought about this as well. Agent may need internet access for log management system (for analysis or crash).

I think we don't need to allow it for now.

Note that the livestream couldn't be live. Given that 10 TPS ticks there is no way to query the system or could easily be avoided using request rate limit.

**Comment by edi9999** [comment]
For log management, we can give users (humans) access to the stdout of their agent after the game is finished. This way, we can give the users the logs, without giving the agents internet access.

**Comment by netgusto** [comment]
Tracked in #102; closing.
