### ISSUE TITLE
Viz: display name of agent (+ life) above agent

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#91]
http://doc.babylonjs.com/extensions/canvas2d_text2d

**Comment by xtuc** [comment]
Agent name passed in https://github.com/ByteArena/bytearena/commit/f64bdde891c3011fe51b1baae1b7f9199cc85d62

**Comment by netgusto** [comment]
Life:
* displayed on a single line at the top of the screen.
* when clicking on an agent, camera follow the clicked agent.

**Comment by netgusto** [comment]
Quick proto to demonstrate the usage of Pixi (2D) as an overlay to Babylon.

[pixi-ui-test.html.zip](https://github.com/ByteArena/bytearena/files/1274519/pixi-ui-test.html.zip)

**Comment by netgusto** [comment]
Done.
