### ISSUE TITLE
Check for collisions

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#93]
Collisions to handle :

* agent / agent
* agent / obstacle
* agent / projectile
* projectile / projectile
* projectile / obstacle

Likely place in code to handle these : `server.go::DoUpdate()`

What happens on collision ?

* Temporary impairment, slowdown ?
* Life consumption ?
* End of game (unlikely) ?

**Comment by xtuc** [comment]
In the real world, collision on a wall is just a brutal velocity reduction (and some damages but ignoring for now). I would use the same behavior.

**Comment by netgusto** [comment]
For efficiency, I think we have to track spatial information in a Quad Tree.

Go packages candidates :

* https://github.com/JamesMilnerUK/quadtree-go (91 🌟)
* https://github.com/aurelien-rainone/go-rquad (69 🌟)
* https://github.com/volkerp/goquadtree (16 🌟)

**Comment by netgusto** [comment]
Quadtree not used, but R-tree; https://github.com/dhconnelly/rtreego

**Comment by netgusto** [comment]
Done:

* Coarse agent/obstacle collision
* Fine agent/obstacle collision
* projectile/obstacle

Left TO DO:

* agent/agent
* agent/projectile
* projectile/projectile

**Comment by netgusto** [comment]
> In the real world, collision on a wall is just a brutal velocity reduction

Yes, see https://gamedev.stackexchange.com/questions/32611/what-is-the-best-way-to-handle-simultaneous-collisions-in-a-physics-engine for how to handle it nicely

**Comment by netgusto** [comment]
Verlet integration for in-motion object pair collision : http://lolengine.net/blog/2011/12/14/understanding-motion-in-games
